name: Médiagrafik
favicon: null
layout_spectrum: 0.8757296213880181
typography_spectrum: 0.3456768924370408
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7180358422920108
  lightness: 0.22715132543817163
  saturation: 0.5738313111942261
  rhythmicContrast: 0.07353889453224838
purpose: []
